from dataclasses import dataclass

@dataclass
class TrainConfig:
    # --- Paths ---
    # Directory where setup.py downloaded the files
    model_dir: str = "./pretrained_models"

    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = "./MyTTSDataset/metadata.csv"
    metadata_path: str = "./WolneLekturyDataset/metadata.json"

    # Directory containing WAV files
    wav_dir: str = "./WolneLekturyDataset/wavs"

    preprocessed_dir = "./preprocess"  # Local storage - fast I/O!
    
    # Output directory for the finetuned model
    output_dir: str = "./chatterbox_output"

    is_inference = True  # Enable inference callback to generate samples during training
    inference_prompt_path: str = "./speaker_reference/1984.wav"
    inference_test_text: str = "Dzień dobry, witam w polskim systemie syntezy mowy."  # Polish test text


    ljspeech = False # Set True if the dataset format is ljspeech, and False if it's file-based.
    json_format = True # Set True if the dataset format is json, and False if it's file-based or ljspeech.
    preprocess = False # If you've already done preprocessing once, set it to false.
    is_turbo: bool = True # Set True if you're training Turbo, False if you're training Normal.

    # --- Vocabulary ---
    # The size of the NEW vocabulary (from tokenizer.json)
    # Ensure this matches the JSON file generated by your tokenizer script.
    # For Turbo mode: Use the exact number provided by setup.py (e.g., 52260)
    new_vocab_size: int = 52260 if is_turbo else 2454 

    # --- Hyperparameters ---
    batch_size: int = 96        # A100 80GB (~69% VRAM)
    grad_accum: int = 1         # effective batch = 96
    learning_rate: float = 1e-5 # T3 is sensitive, keep low
    num_epochs: int = 100

    save_steps: int = 500
    save_total_limit: int = 3
    dataloader_num_workers: int = 8  # A100 80GB

    # --- Constraints ---
    start_text_token = 255
    stop_text_token = 0
    max_text_len: int = 256
    max_speech_len: int = 850   # Truncates very long audio
    prompt_duration: float = 3.0 # Duration for the reference prompt (seconds)
