import os
from dataclasses import dataclass

@dataclass
class TrainConfig:
    # --- Paths ---
    # Directory where setup.py downloaded the files
    model_dir: str = os.getenv("MODEL_DIR", "./pretrained_models")
    
    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = os.getenv("CSV_PATH", "./MyTTSDataset/metadata.csv")
    
    # Directory containing WAV files
    wav_dir: str = os.getenv("WAV_DIR", "./MyTTSDataset/wavs")
    
    preprocessed_dir = os.getenv("PREPROCESS_DATASET_DIR", "./MyTTSDataset/preprocess")
    
    # Output directory for the finetuned model
    output_dir: str = os.getenv("OUTPUT_DIR", "./chatterbox_output")

    ljspeech = True

    # --- Hyperparameters ---
    batch_size: int = 4         # Adjust based on VRAM (2, 4, 8)
    grad_accum: int = 2        # Effective Batch Size = Batch * Accum
    learning_rate: float = 5e-5 # T3 is sensitive, keep low
    num_epochs: int = 200

    # --- Constraints ---
    start_text_token = 255
    stop_text_token = 0
    max_text_len: int = 256
    max_speech_len: int = 850   # Truncates very long audio
    prompt_duration: float = 3.0 # Duration for the reference prompt (seconds)

    # --- Vocabulary ---
    # The size of the NEW vocabulary (from tokenizer.json)
    # Ensure this matches the JSON file generated by your tokenizer script.
    new_vocab_size: int = 2454